# Generated by Django 4.1.4 on 2022-12-28 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name Surname')),
                ('image', models.ImageField(upload_to='announcer_images', verbose_name='Image')),
                ('work', models.CharField(max_length=10000, verbose_name='Work name')),
                ('linkedin_link', models.CharField(max_length=500, verbose_name='Linkedin link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('cover_image', models.ImageField(upload_to='events_cover_images', verbose_name='Cover Image')),
                ('des_image', models.ImageField(upload_to='events_des_images', verbose_name='Des Image')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(editable=False, max_length=256, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name Surname')),
                ('image', models.ImageField(upload_to='media/mentors_images', verbose_name='Image')),
                ('work', models.CharField(max_length=10000, verbose_name='Work name')),
                ('linkedin_link', models.CharField(max_length=500, verbose_name='Linkedin link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name Surname')),
                ('image', models.ImageField(upload_to='media/trainers_images', verbose_name='Image')),
                ('work', models.CharField(max_length=500, verbose_name='Work name')),
                ('linkedin_link', models.CharField(max_length=500, verbose_name='Linkedin link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
