# Generated by Django 4.1.4 on 2022-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=256, verbose_name='Your Name and Surname')),
                ('email', models.EmailField(max_length=60, verbose_name='Your e-mail')),
                ('number', models.CharField(max_length=30, verbose_name='Your Phone')),
                ('project_name', models.CharField(max_length=256, verbose_name='Project name')),
                ('project_des', models.TextField(max_length=20000, verbose_name='Project description')),
                ('team_members', models.TextField(max_length=10000, verbose_name='Team members')),
                ('project_level', models.TextField(max_length=15000, verbose_name='What stage was...')),
                ('file', models.FileField(upload_to='media/file', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Your Email')),
                ('number', models.CharField(max_length=20, verbose_name='Your Phone')),
                ('message', models.TextField(max_length=5000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
