# Generated by Django 4.1.4 on 2022-12-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Your Email')),
                ('number', models.CharField(max_length=20, verbose_name='Your Phone')),
                ('message', models.TextField(max_length=5000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name Surname')),
                ('image', models.ImageField(upload_to='media/mentors_images', verbose_name='Image')),
                ('work', models.CharField(max_length=10000, verbose_name='Work name')),
                ('linkedin_link', models.CharField(max_length=500, verbose_name='Linkedin link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name Surname')),
                ('image', models.ImageField(upload_to='media/trainers_images', verbose_name='Image')),
                ('work', models.CharField(max_length=500, verbose_name='Work name')),
                ('linkedin_link', models.CharField(max_length=500, verbose_name='Linkedin link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
