# Generated by Django 4.1.4 on 2022-12-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='choice',
            field=models.CharField(choices=[('1', 'choice1'), ('1', 'choice2'), ('2', 'choice3'), ('Other', 'Other Please Specify')], max_length=250, verbose_name='Selected your choice'),
        ),
    ]
