# Generated by Django 4.1.4 on 2022-12-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_apply_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='file',
        ),
    ]
