# Generated by Django 4.1.4 on 2022-12-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_apply_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='choice',
        ),
        migrations.AddField(
            model_name='apply',
            name='idea',
            field=models.CharField(default=1, max_length=530, verbose_name='What field is your idea / product / service in?'),
            preserve_default=False,
        ),
    ]
