# Generated by Django 4.1.4 on 2022-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_apply_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='file',
            field=models.FileField(default=1, upload_to='file', verbose_name='File'),
            preserve_default=False,
        ),
    ]
